### ISSUE TITLE
Qt5ct > config app

### ISSUE THREAD

**Issue by Ste74** [manjaro/manjaro-gnome-settings#1]
Hi guys , in order to solve this [issue](https://forum.manjaro.org/t/unstable-mate-1-18-in-repo-and-on-iso/19836/28) for mate i have also checked for gnome and budgie . I know the tread where we have adopt the solution to export the qt5 override into the .profile file and the qt5 app work fine but in this three DE if not set also the override into /etc/environment the app to config the qt5 style not work ..  so why not use also this entry ? [what is the reason ?](https://github.com/manjaro/release-plan/issues/73#issuecomment-231221460)
@philmmanjaro , @Kirek , @udeved

**Comment by udeved** [comment]
Can you please post from a running mate session

    printenv

**Comment by Ste74** [comment]
Here is

```
[stemate@ste74 ~]$ printenv
LANG=it_IT.UTF-8
MANAGERPID=904
DISPLAY=:1
INVOCATION_ID=2d657e78[stemate@ste74 ~]$ printenv
LANG=it_IT.UTF-8
MANAGERPID=904
DISPLAY=:1
INVOCATION_ID=2d657e78dba84aa3a577c1a6912f5df4
GTK_OVERLAY_SCROLLING=0
COLORTERM=truecolor
SSH_AUTH_SOCK=/run/user/1001/keyring/ssh
USER=stemate
PWD=/home/stemate
HOME=/home/stemate
JOURNAL_STREAM=8:18743
MATE_DESKTOP_SESSION_ID=this-is-deprecated
DBUS_STARTER_ADDRESS=unix:path=/run/user/1001/bus,guid=8bbbc5bd9017d4dfe31e923058d043c4
MAIL=/var/spool/mail/stemate
SHELL=/bin/bash
VTE_VERSION=4601
TERM=xterm-256color
DBUS_STARTER_BUS_TYPE=session
SHLVL=1
WINDOWID=54525958
LOGNAME=stemate
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1001/bus,guid=8bbbc5bd9017d4dfe31e923058d043c4
XDG_RUNTIME_DIR=/run/user/1001
XAUTHORITY=/run/user/1001/gdm/Xauthority
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
SYSTEMD_NSS_BYPASS_BUS=1
SESSION_MANAGER=local/ste74:@/tmp/.ICE-unix/927,unix/ste74:/tmp/.ICE-unix/927
_=/usr/bin/printenv
[stemate@ste74 ~]$ ^C
[stemate@ste74 ~]$ 
dba84aa3a577c1a6912f5df4
GTK_OVERLAY_SCROLLING=0
COLORTERM=truecolor
SSH_AUTH_SOCK=/run/user/1001/keyring/ssh
USER=stemate
PWD=/home/stemate
HOME=/home/stemate
JOURNAL_STREAM=8:18743
MATE_DESKTOP_SESSION_ID=this-is-deprecated
DBUS_STARTER_ADDRESS=unix:path=/run/user/1001/bus,guid=8bbbc5bd9017d4dfe31e923058d043c4
MAIL=/var/spool/mail/stemate
SHELL=/bin/bash
VTE_VERSION=4601
TERM=xterm-256color
DBUS_STARTER_BUS_TYPE=session
SHLVL=1
WINDOWID=54525958
LOGNAME=stemate
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1001/bus,guid=8bbbc5bd9017d4dfe31e923058d043c4
XDG_RUNTIME_DIR=/run/user/1001
XAUTHORITY=/run/user/1001/gdm/Xauthority
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
SYSTEMD_NSS_BYPASS_BUS=1
SESSION_MANAGER=local/ste74:@/tmp/.ICE-unix/927,unix/ste74:/tmp/.ICE-unix/927
_=/usr/bin/printenv
[stemate@ste74 ~]$ 

```

**Comment by udeved** [comment]
Do you try to export `$QT_QPA_PLATFORMTHEME `in this mate session?
And if, in what file?

**Comment by Ste74** [comment]
Sorry for delay :) ,yesterday after play with gdm to do a theme for manjaro i have break my system :D .. 
After manage in console i come back again :p .. so i have exported the override in the .profile file in according with manjaro-base-skel right ?

**Comment by udeved** [comment]
Yes, but you probably have to put it somewhere else, eg ~.bashrc.

**Comment by Ste74** [comment]
I have open a ticket here 
https://sourceforge.net/p/qt5ct/tickets/35/
i try to add in .bashrc , .pam_environment and also in .xinitrc but nothing change .. if i want open the app ( i.e. qt5ct ) via control center of mate and also in gnome i have to add the override in /etc/environment :\  . Any issue if add this override only in my de s  ?

**Comment by Ste74** [comment]
After other test at the moment only Mate is affected so i put the overlay only for mate 
https://github.com/manjaro/iso-profiles/commit/cca311f88a3967c37f174791b5b309b681b696bf
