### ISSUE TITLE
The top panel after the last manjaro update began to look like this (with many shell themes)

### ISSUE THREAD

**Issue by darleneeon** [manjaro/manjaro-gnome-settings#10]
![issue](https://user-images.githubusercontent.com/29887971/31056432-93f4a406-a6fb-11e7-9e9d-fc1e3ef17398.png)
![issue2](https://user-images.githubusercontent.com/29887971/31056430-938d1426-a6fb-11e7-8b70-4fe39bbd5783.png)

**Comment by Ste74** [comment]
Remove `manjaro-gnome-maia-theme` if installed .. what is your theme ?

**Comment by darleneeon** [comment]
@Ste74 nothing changed. My theme is [United](https://github.com/godlyranchdressing/United-GNOME), but issue affects all themes (even Arc), except [Adapta](https://github.com/adapta-project/adapta-gtk-theme).

**Comment by Chrysostomus** [comment]
I have the issue too. After installing the gdm theme, all shell themes have some wrong colors. Removing doesn't fix it.

**Comment by darleneeon** [comment]
@Chrysostomus yes, gdm theme was updated

**Comment by Ste74** [comment]
@darleneeon sorry not understand if after remove manjaro-gnome-maia-theme and rebooted all is fine :( ..

**Comment by darleneeon** [comment]
@Ste74 so how to fix it now?

**Comment by philmmanjaro** [comment]
Is it a dark settings issue? Checked with gnome tweak tool yet to set it to light mode?

<img src="http://surfontech.com/osreviews/gnometweaktoolFedora22.png">

**Comment by darleneeon** [comment]
@philmmanjaro no it's not
![image](https://user-images.githubusercontent.com/29887971/31074680-07a5a0da-a79c-11e7-8e63-e98b185bca95.png)

**Comment by philmmanjaro** [comment]
Maybe activate it, as this option is changing the font for dark themes. Seems the used theme is dark and the option should be on by default. Enable it and re-login.

**Comment by darleneeon** [comment]
@philmmanjaro no, it doesn't solve the issue

**Comment by darleneeon** [comment]
@Ste74 @Chrysostomus @philmmanjaro the only way I see is to reinstall the whole system

**Comment by Ste74** [comment]
In our forum i have this report 
https://forum.manjaro.org/t/stable-update-2017-09-30-timeshift-kernels-nvidia-jade-haskell-jdk9-snap-support/32109/73
So the first version of `manjaro-gnome-settings` enable by default the theme but this is wrong and i have correct it . The new version save the `gresource` filein gnome-shell and when you remove the `manjaro-gnome-adapta-maia-theme `the `gresource` shell ( original ) is reimplemented . So what conatin your usr/share/gnome-shell folder after remove the` manjaro-gnome-adapta-maia-theme ` ? At last you can remove the gresource file ( any reference ) and reinstall gnome-shell ( this contain the gresource vanilla ) ..

**Comment by darleneeon** [comment]
@Ste74 i tried to reinstall gnome shell, but now gdm login just log me out when i am trying to log in

**Comment by Ste74** [comment]
Rename the `Default` file in `/etc/gdm/PostLogin folder `

**Comment by darleneeon** [comment]
@Ste74 no, it doesn't work :)
