### ISSUE TITLE
Consider changing shell theme

### ISSUE THREAD

**Issue by Chrysostomus** [manjaro/manjaro-gnome-settings#13]
I have been running some experiments over a couple of weeks, and have come to conclusion that using the gnome shell theme adapta-maia (and its variants) leads to frequent crashing of gnome shell. I have gotten 4 interrupted pacman updates because of this and some data loss. The issue goes away when using the default shell theme. 

I think we should consider changing the theme to something more stable (even though adapta-maia looks great).

**Comment by Ste74** [comment]
Hi , have you tried to use with our default extensions and also without postlogin script ( i don't this this is related but i have removed and setting wayland as default ). I can't trace this issue but since adapta ( upstream ) is designed with priority for Gnome can be usefull report on upstream..

**Comment by Chrysostomus** [comment]
With the latest update (which modified also gdm) the default shell theme was modified, making the stable adwaita theme inaccessible. I can't say I'm a fan of that. Pure white menus and calendar kind of stand out from the rest of the desktop, although legibility of the calendar is admittedly better.

**Comment by Ste74** [comment]
Yes GDM theme is related at gnome-shell theme so the only way to "branding" GDM was apply a gresource files to override the default GDM shell theme. The `manjaro-gnome-maia/breath-theme` modify this theme but this is designed for Adapta theme so any other shell theme can the look ugly. We can write a message to inform users ?

**Comment by Chrysostomus** [comment]
Maybe, but you also need a post removal script to clean it afterwards in case someone doesn't want it. I think it is a risky idea in the first place, because it

1) breaks the default theme and many others
2) causes instability.

**Comment by Ste74** [comment]
Please check this 
https://github.com/Ste74/manjaro-gnome-theme
The removal hook..

**Comment by Ste74** [comment]
Sorry my smartphone :p

**Comment by Chrysostomus** [comment]
Does not work. The script reverts to the previous custom gdm theme. Also, the hook does not trigger the script.

**Comment by Chrysostomus** [comment]
There is something wrong with the install script. It is supposed to save the old configuration in gnome-shell-theme.gresource. However, I've got no such file in my filesystem.

**Comment by Chrysostomus** [comment]
Correction, the hook works, it was just provided by a different package than I thought.

**Comment by Chrysostomus** [comment]
Btw, If we are to change the shell, could we not just take default adwaita, change blue to green and call it a day?

**Comment by Ste74** [comment]
Let me try to change the default GDM theme.. then i submit you to test 💨

**Comment by Ste74** [comment]
😉

**Comment by Ste74** [comment]
Damn it sorry again

**Comment by Chrysostomus** [comment]
It happens

**Comment by Ste74** [comment]
@Chrysostomus please copy the grsource file from here and give me your feedback ;)
https://github.com/Ste74/manjaro-gnome-theme/tree/master/new-approach/theme

**Comment by Chrysostomus** [comment]
Thanks, I will

**Comment by Chrysostomus** [comment]
It appears to work as intended. Custom theme in gdm, maia colors in gnome-shell. I'll need a bit more time to see if it is as stable as we hoped, but if it is, I think we could use this.

**Comment by Ste74** [comment]
Good .. do you think for the choice color of user ? Maia color is right or better another green more light?

**Comment by Chrysostomus** [comment]
I think the color is good

**Comment by Chrysostomus** [comment]
Stabillity has been good thusfar, it has managed to work now about 15 hours straight without problems. Shell reloaded once, but that was harmless, as no apps were closed and no user was signed off.

**Comment by Ste74** [comment]
close via https://github.com/manjaro/packages-community/commit/a2e36267176d2c1db0d1ad03de4aacfcb11627d9

reopen if needed :)
