### ISSUE TITLE
manjaro-gnome-extension-settings cyclic depend-needs on manjaro-gnome-settings

### ISSUE THREAD

**Issue by petsam** [manjaro/manjaro-gnome-settings#14]
`manjaro-gnome-settings` cannot be uninstalled without removing `manjaro-gnome-extension-settings`
`manjaro-gnome-settings` depends on and is required from `manjaro-gnome-extension-settings`
`manjaro-gnome-extension-settings` should be standalone package and have any settings needed from `manjaro-gnome-settings` merged to it.
I hope I describe it well, but you can get the issue.
This setup makes installing another manjaro desktop settings package impossible.
Unless it is a feature, so it would be nice to acknowledge the reason.
Thanks
and Merry Christmas!!

Edit: seems related to this https://github.com/manjaro/manjaro-gnome-settings/pull/4

**Comment by Ste74** [comment]
Uhmm you have right .. i think i can remove the depends on `manjaro-gnome-extension-settings`

**Comment by Ste74** [comment]
Closed via https://github.com/manjaro/packages-community/commit/972ce038ed9bb53edaa1072ba485c0678d147195
:wink:
