### ISSUE TITLE
Suggested desktop setup

### ISSUE THREAD

**Issue by es20490446e** [manjaro/manjaro-gnome-settings#8]
## The desktop

With the purpose of enhancing ease of use, and usability when managing plenty of windows, I made the following desktop setup:

- [Empty desktop](https://i11.servimg.com/u/f11/16/19/87/90/screen10.jpg)
- [File manager](https://i11.servimg.com/u/f11/16/19/87/90/screen10.png)
- [Applications menu](https://i11.servimg.com/u/f11/16/19/87/90/screen12.jpg)
- [Status bar menu](https://i11.servimg.com/u/f11/16/19/87/90/screen11.jpg)

Which can be tested using [this installer](https://github.com/manjaro/manjaro-gnome-settings/files/1159706/Minimal.Manjaro.GNOME.interface.zip).

## Motivation

In the beginning I made it for my own convenience and for my friends. But I thought that perhaps you will find some these concepts interesting, and borrow some of them as liked.

Probably I would be finally using KDE plasma instead as my recommended desktop environment. As it recovers more gracefully from crashes, has a more regular performance, it's applications are more portable across platforms, has less bugs, it's more versatile, and finally it doesn't remove features that truly makes life easier.

Even then I have all the intuition that many people using GNOME would find this setup very appealing, and much more easygoing than the default GNOME desktop.

Note that the purpose wasn't to make the interface minimalist, but rather that was a collateral result of fitting it to true usage.

## Design principles

Lastly more important than the end result, I think it's knowing the [ideas behind it](https://plus.google.com/+AlbertoSalviaNovella/posts/JsN2LwvyZJ8).

**Comment by Ste74** [comment]
Thank you for your suggestions! My vision of Manjaro Gnome is that it should be different enough from other dostros‘ Gnome. I don‘t see enough difference in the settings you suggested. I will keep in mind what you suggested and see what I might want to implement. Thank you!
