### ISSUE TITLE
Nautilus configuration

### ISSUE THREAD

**Issue by Chrysostomus** [manjaro/manjaro-gnome-settings#9]
There have been requests of 

- sort folders before files
- typeahead support
- files in ~/Templates/ for empty text file and shellscript.sh

**Comment by Ste74** [comment]
Hi matty.. for me is holidy time, i come back at my home and at my pc only after the 21/8... anyway the first issue is simple to solve: is a key in gsettings to modify.
The second i not understand fine what you mean and for the third issue not work the actual empty file wirkaround for gnome and deepin ? nautlis-empty-file pkg?

Stefano :)

**Comment by Chrysostomus** [comment]
1) as you said 
2) would be aur package nautilus-typeahead. It re-enables typeahead, meaning that when you start typing in nautilus, you don't automatically do recursive file search, but instead select a file in the current folder that matches to what you typed. Normal file search is accessed with ctrl+f. Install nautilus-typeahead and see what I mean. 
3) I thought this could be done with just adding empty `/etc/skel/Templates/empty\ file`. Do you mean that this might not work because of location differences?

**Comment by Chrysostomus** [comment]
I uploaded the nautilus-typeahead to unstable repos in case you are interested in testing it once you have the time.

**Comment by Ste74** [comment]
Yep, sure i want test :) .. for the empty file yes @oberon2007 create this pkg as a workaround for the locale translations.. templates is not equal when user choice the localization ... with the same prunciple we can create another pkg to do the bash template file or modify the old for do togheter the template...

**Comment by Ste74** [comment]
@Chrysostomus for shellscript.sh you mean a template with this content at first line ? : 
#!/bin/bash

**Comment by Chrysostomus** [comment]
Yes

**Comment by Ste74** [comment]
Well , two of three correction are in unstable , sort directory before files done and also a Empty Bash file come  with my last commit : nautilus-empty-file pkg create two template now ..
for nautilius-typehead not sure if we have to maintain because i read also canonical drop the patch because this patch have to be rebuild any time a new nautilus release is out ( ubuntu 17.10 drop it ) :\

**Comment by Chrysostomus** [comment]
Okay. We don't have the resources to maintain without upstream source. So probably no then.

**Comment by Ste74** [comment]
@Chrysostomus since we have gtk3-classic pkgs we should close this . Re-open if needed

**Comment by Chrysostomus** [comment]
I think gtk3-classic solves it only for the file chooser dialog and not nautilus. But since we agreed we cannot maintain it, the issue should be closed anyway.
